import { useState } from 'react'
import type { Letter } from '../../../shared/types'

interface Props {
  letter: Letter
}

function generateAdvisorSummary(letter: Letter): string {
  const deadline = letter.deadline
    ? new Date(letter.deadline).toLocaleDateString('de-DE', { day: 'numeric', month: 'long', year: 'numeric' })
    : 'Not detected'

  const daysLeft = letter.deadline
    ? Math.ceil((letter.deadline - Date.now()) / 86_400_000)
    : null

  const deadlineUrgency = daysLeft !== null
    ? (daysLeft < 0 ? ' (OVERDUE)' : daysLeft === 0 ? ' (TODAY)' : daysLeft <= 7 ? ` (${daysLeft} days left)` : ` (${daysLeft} days left)`)
    : ''

  const lines: string[] = [
    '═══════════════════════════════════════',
    '  BriefKlar — Letter Analysis Summary',
    '═══════════════════════════════════════',
    '',
    `Letter Type:  ${letter.type_label ?? 'Unknown'}`,
    `Urgency:      ${(letter.urgency ?? 'medium').toUpperCase()}`,
    `Sender:       ${letter.sender ?? 'Unknown'}`,
    `Deadline:     ${deadline}${deadlineUrgency}`,
  ]

  if (letter.amount != null) {
    lines.push(`Amount:       €${letter.amount.toLocaleString('de-DE', { minimumFractionDigits: 2 })}`)
  }

  lines.push(
    `Scanned:      ${new Date(letter.scanned_at).toLocaleDateString('de-DE')}`,
    `Status:       ${letter.status === 'done' ? 'Handled' : 'Pending'}`,
    '',
  )

  if (letter.what_it_is) {
    lines.push('WHAT THIS IS:', letter.what_it_is, '')
  }

  if (letter.what_to_do?.length) {
    lines.push('WHAT TO DO:')
    letter.what_to_do.forEach((step, i) => {
      lines.push(`  ${i + 1}. ${step}`)
    })
    lines.push('')
  }

  if (letter.consequence) {
    lines.push('IF IGNORED:', letter.consequence, '')
  }

  if (letter.free_help?.length) {
    lines.push('FREE HELP:')
    letter.free_help.forEach((tip) => {
      lines.push(`  • ${tip}`)
    })
    lines.push('')
  }

  lines.push(
    '───────────────────────────────────────',
    'Generated by BriefKlar · Not legal advice',
    'Always verify deadlines independently',
  )

  return lines.join('\n')
}

export default function ShareSummary({ letter }: Props) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    const summary = generateAdvisorSummary(letter)
    await navigator.clipboard.writeText(summary)
    setCopied(true)
    setTimeout(() => setCopied(false), 3000)
  }

  const handleExportPdf = async () => {
    await window.briefklar.exportAnalysisPdf(letter.id)
  }

  return (
    <div className="bg-white border border-surface-border rounded-2xl p-4 mb-4">
      <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">
        Share with Advisor
      </h3>
      <p className="text-xs text-slate-500 mb-3">
        Copy a plain-text summary to share with a Migrationsberater, Schuldnerberatung, lawyer, or social worker.
      </p>
      <div className="flex gap-2">
        <button
          type="button"
          onClick={handleCopy}
          className="flex-1 border border-surface-border text-slate-700 hover:bg-slate-50 text-sm font-medium py-2 rounded-xl transition-colors"
        >
          {copied ? '✓ Copied!' : '📋 Copy Summary'}
        </button>
        <button
          type="button"
          onClick={handleExportPdf}
          className="flex-1 border border-surface-border text-slate-700 hover:bg-slate-50 text-sm font-medium py-2 rounded-xl transition-colors"
        >
          📄 Export PDF for Advisor
        </button>
      </div>
    </div>
  )
}
